import { Station } from './types';

export const mockStations: Station[] = [
  {
    id: 'chevron-valley',
    name: 'Chevron — Valley Boulevard',
    distance: '0.4 mi',
    cleanlinessTier: 'clean',
    score: 4.5,
    ratingCount: 128,
    freshnessHours: 2,
    safetyBadges: ['Lot well lit', '24/7', 'Staff on site', 'Visible from road'],
    subRatings: {
      clean: 5,
      friendly: 4,
      convenient: 4,
    },
    latitude: 30,
    longitude: 45,
    reviews: [
      {
        id: 'rev-1',
        username: 'SarahDrivesAlone',
        avatarInitials: 'SD',
        timestamp: '2h ago',
        text: 'Super clean restrooms, bright LED lighting outside. Felt very safe coming here at 11 PM to refuel and stretch.',
        score: 5,
        helpfulCount: 24,
      },
      {
        id: 'rev-2',
        username: 'RoadWarrior99',
        avatarInitials: 'RW',
        timestamp: '1d ago',
        text: 'Clean floor, fully stocked toilet paper, and the hand dryer actually works. Indoor entrance near the register.',
        score: 4,
        helpfulCount: 12,
      },
    ],
  },
  {
    id: 'shell-crossing',
    name: 'Shell — North Crossing',
    distance: '1.2 mi',
    cleanlinessTier: 'mixed',
    score: 3.2,
    ratingCount: 64,
    freshnessHours: 18,
    safetyBadges: ['Indoor entrance', 'Staff on site', '24/7'],
    subRatings: {
      clean: 3,
      friendly: 3,
      convenient: 4,
    },
    latitude: 65,
    longitude: 25,
    reviews: [
      {
        id: 'rev-3',
        username: 'TransitMama',
        avatarInitials: 'TM',
        timestamp: '18h ago',
        text: 'Restrooms are indoor, which is nice for safety. However, cleanliness was mediocre. Needs a good sweep and restocking.',
        score: 3,
        helpfulCount: 15,
      },
      {
        id: 'rev-4',
        username: 'EchoTracer',
        avatarInitials: 'ET',
        timestamp: '3d ago',
        text: 'Average station. Staff was friendly but restroom smelled a bit like old damp cleaner. Safe but not pristine.',
        score: 3.5,
        helpfulCount: 8,
      },
    ],
  },
  {
    id: 'valero-exit14',
    name: 'Valero — Exit 14',
    distance: '1.5 mi',
    cleanlinessTier: 'gross',
    score: 1.8,
    ratingCount: 32,
    freshnessHours: 6,
    safetyBadges: ['Outdoor entrance', 'Visible from road'],
    subRatings: {
      clean: 1.5,
      friendly: 2,
      convenient: 3,
    },
    latitude: 45,
    longitude: 80,
    reviews: [
      {
        id: 'rev-5',
        username: 'NightCruiser',
        avatarInitials: 'NC',
        timestamp: '6h ago',
        text: 'Avoid if possible. Restroom is outdoor around the back and very poorly lit. Trash was overflowing and no soap.',
        score: 1,
        helpfulCount: 42,
      },
      {
        id: 'rev-6',
        username: 'SoloGal7',
        avatarInitials: 'SG',
        timestamp: '2d ago',
        text: 'Dirty floors, lock on the door was loose. I felt uncomfortable since it is behind the main building.',
        score: 2,
        helpfulCount: 29,
      },
    ],
  },
  {
    id: 'texaco-route9',
    name: 'Texaco Express — Route 9',
    distance: '2.1 mi',
    cleanlinessTier: 'unrated',
    score: 0.0,
    ratingCount: 0,
    freshnessHours: 0,
    safetyBadges: ['Lot well lit', '24/7', 'Visible from road'],
    subRatings: {
      clean: 0,
      friendly: 0,
      convenient: 0,
    },
    latitude: 80,
    longitude: 60,
    reviews: [],
  },
  {
    id: 'bp-avon',
    name: 'BP Travel Center — Avon',
    distance: '0.8 mi',
    cleanlinessTier: 'clean',
    score: 4.1,
    ratingCount: 96,
    freshnessHours: 12,
    safetyBadges: ['Lot well lit', '24/7', 'Indoor entrance', 'Staff on site'],
    subRatings: {
      clean: 4,
      friendly: 4,
      convenient: 5.0,
    },
    latitude: 20,
    longitude: 70,
    reviews: [
      {
        id: 'rev-7',
        username: 'AvonLocal',
        avatarInitials: 'AL',
        timestamp: '12h ago',
        text: 'Decent stop, very bright parking lot. Restrooms inside are usually clean. Staff is always at the counter.',
        score: 4,
        helpfulCount: 18,
      },
    ],
  },
];
